### ISSUE TITLE
FluentWait.until not working with newer version of Selenium 3.4.0

### ISSUE THREAD

**Issue by aquddos123** [FluentLenium/FluentLenium#513]
We are using Fluent wait in our project like below which was working fine with Selenium 2.53.1 so far. But with our recent upgrade to Selenium 3.4.0 it stopped working. 
`await().atMost(maxWaitImeInSeconds, TimeUnit.SECONDS).until("#some-id").isNotPresent();`

We are seeing the following exception now:

```
__EXCEPTION__:java.lang.NoSuchMethodError: org.openqa.selenium.support.ui.FluentWait.until(Lcom/google/common/base/Predicate;)V
	at org.fluentlenium.core.wait.FluentWait.until(FluentWait.java:98) [fluentlenium-core-0.10.3.jar]
	at org.fluentlenium.core.wait.FluentWaitMatcher.until(FluentWaitMatcher.java:70) [fluentlenium-core-0.10.3.jar]
	at org.fluentlenium.core.wait.FluentWaitMatcher.isNotPresent(FluentWaitMatcher.java:195) [fluentlenium-core-0.10.3.jar]

```

I've tried with the updated guava dependency to 21 version as mentioned in the [ selenium/java/CHANGELOG](https://github.com/SeleniumHQ/selenium/blob/master/java/CHANGELOG#L18-L19) but that didn't work. 

Is there any change required in the syntax of Wait call I have to update? Any idea how can I change the about script to make it working?

Thanks.

**Comment by Toilal** [comment]
It seems your are using a really outdated FluentLenium version. You have to latest FluentLenium 3.x version, there's a migration guide in docs from 0.x.

**Comment by filipcynarski** [comment]
As @Toilal wrote @aquddos123 it is right time to update your FluentLenium enjoy!
